language: ruby
rvm:
- 2.2.3
script: bundle exec rspec spec

deploy:
  provider: heroku
  api_key:
  - secure: uu3BdfNIEEZ1WDbnpsWrW+hd5jSci8DjcMxjM/Ne4Ea6Y5XJcK8oGprG2oT8v02SGCVgnS2NOv/plw0+zFqKOdPufXkHH+ungO65tqRprhWbJsiNwFKzlJlZn+3Up8ibDKO00KG/BpEV0408ZlFmRwWjGHLOFZjN0qPOg2r4HNW4q0tXZt89B+Xinsquxi7aznrMSBTPueW2s/8fIGGeD+vXK9fe0I1H+0LlP949lWBTfop3bxA49H/GoLVIeQXy63JBvVjcZWvgYkqyAtysBaZZkNsdIt1T0oi43n/KoVXbuIo0j4ycOYoswOa7dqSXHqd81ZzOEGM3WZK4FisBUBTikfC6ZLZ2TErYSqzTj2JZX+2gbmJ1G2naaYyVdfZxlC7y5yv0TOxkfEOcDhQh2yDAXzTiRX9a9KRLKNUjXDHyFJ4Mez5f13VrvamaY2cMkzUN5BzsS0Kih4UHCfgJavmJUGbqjwYSGs4b4SdHXMiWl3r5oaci9Gw83G8zDW37Oe6un6+EfEpUBszsxeEuxKnjRsX8K5mecmHPzCldPPKr+JTpxDuS/72yU1OVX5Ci2FqOQXZybD0SxcCFGftrbyL7kOjkYI24emB4D+A9TCHicUdcq870Nu5mMRq+vD++TCfbBVuA3gIlj8oVkgNLkvrlEeYGu9rI1PVRr0x6cRQ=
