language: ruby
rvm:
- 2.2.3
script: bundle exec rspec spec

deploy:
  provider: heroku
  api_key:
    secure: M41AOO6xwZYh3lkEePhjUjZZbW7b6JtSMDwnnFriDP5u83nJmqYKKENcrgr09r98xv9ORt9FTtSZEcG4iFCxQI+jzUAKR/5pMb+kK4RbNzSdQTDTwjpCExf7pC2AsK/gHUMd200MYrrLM2XcpPkUHYGmj/jhytMOLTiWQ4sW5HO3uWK7lmTIoiFamfCyMvRJaSWdoCBQj6XQvFfZyCgyfa9r84jDqTHkQsf/8413spF9QQqAoPrkIh1t4oDy0EXO7h9lbB3VcfweTKX5nnXYwbCcmVwTi4O07WHNaE1s0yPempfUx8FaGWLhNqGWzU8kGGJ6aU+4qfpaUZOpFb9E5wxKe/0u2khPFAytRTICKZqKrYBCtt44/f7ICQw56KZJ2lt3YZO4Xk3tyGsRd5sbrfWTFsTtv9fdLZZRYLA29lWtO9D4oJYAji+tBoqisPQkLyj8yix+Dx8xfz7fSwYcJHm1bYcDLzkilQ+gnD79nHiAW8dfywR2RGpwgR6L2PlXs3hZHd8WlRQ0l87M80/fGjWdmefPvte1kQqmlA5LuWHZnxVX2wXvpHfUUosMZn2iSD8fxBj+l4PfxE5bbjBRQoh5lt7xhkYdaBfOE6kPZavTxC4olKeSgQOIVPCWHv/v9cD7OFLeRdOFT/Lt1nCbNnmSjZN6jWnYT+4xXrPaQu4=
