version: 2
jobs:
  build:
    working_directory: ~/strava_tfl
    docker:
      - image: circleci/ruby:2.5.3-node
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: ruby-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: ruby-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter --out /tmp/test-results/rspec.xml \
                            --format json --out /tmp/test-results/output.json \
                            --format html --out /tmp/test-results/report.html \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      
      - type: store_artifacts
        path: /tmp/test-results
        
      - type: store_test_results
        path: /tmp/test-results
