
app: https://stravatfl.herokuapp.com
# app: http://localhost:9393

authentication:
  client_id: 1111
  response_type: code
  scope: write
  state: login
  redirect_uri: /authorization
  client_secret:

endpoint:
  strava_api: https://www.strava.com
  authorize: /oauth/authorize
  deauthorization: /oauth/deauthorize
  token_exchange: /oauth/token
  callback: /auth/callback
